---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-backup-token
  namespace: quantified-self
spec:
  encryptedData:
    token: AgBeQTiPEUMRVuQqWkydfWDrZuMqYl4NLREug9jsISXLJXOU5gBVCLouQ/VmAhbpxYzfIZqz3HcoJaELvIZkooZD6dWwK5WfEGMxGV2IhiZTuidPGmSXUjgFDxOjfTG2LJpqe8omeZ/qItlXfrHBeGx099nLJRxtdkDqcw93CfQVEwBOcm63mu+lag5vMMLdf5T/Ezdr10/WSdNj2ik0Gv6zm9sTuUldqeu+IKzJGnTqp/bsPrBYJGhW4Dt81hOCjn3V15bO0Ihj2LqKaosPBcW7v44F0210BM8kDuF/WLdTHIgTFsIkJ9tgYJnMVJ6TOPyndXrYjUBZDI0U5T60GUwbdX9gUNmdLghT+cM8ogJiv0yK0emG49gDUSm5gJ5iiGbYMeTSOrmk1y/FBusG3oa8Aqe2KDcQBScB85AmR27R29PqcrL2ijZWmub6vbruzkqZnicRB5H8eWsQZYrUktjOoTdSGBCVOPf3yejCUf6gsi7PyLII6iNOgOaN26qOIvN1S4shWACXSOxQeOs/KF7cN4jvfuzq9cdYyI7w5R+OpnrppfmUaemYdxRWsRd3/Q2AiiFJX28lYQwx0bp3Eks4XjZfCcaOTKdJciF0Emc9xCxDp2Cd+lJ4Ow4V7m6SClBLhPXWEU7haGeTkYKyS1elX2fLY5YOgUl5JZN7NYKQBYUmvKtr2g30Yth5owPIc8Yy1C29VxAFH3Ac5YSQK9bhyX7r3DRpeQhmiuAFXNaYLpuxsxM+lw7FIj2KP3qFLJlccm/teon1DYR9SIrD8kGduEhx+F0g0LwPI1Wcd7BD8vuHyruLPtg3
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-backup-token
      namespace: quantified-self
