---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-encryption-key
  namespace: quantified-self
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCnl4rZEp1+8kvCcoKRBx/8zX7DI39vMxOSW5lN2BESSGkJUPM/KBSYy/eAFmwYFxb3pf/NrnWLGy+C0yGl8HCath14yDC7YliQTxadErlFPcS5oOgBaBbEmAdpcBb3ouuto2V4eB52SWtqTniPh++HDl5Fvt6n9UasX+ELIVYkFl86t+FztXQvybKINf9og5q+zrzg6p0Xigz20O1MEoM1aX63McHr3Ef85ZxnYota05T8aBZLpxIH7EPY8+QMN88tlcSOD0RXOmdW/ZnkiHodN9jr49KvRjAy5xqbVOJTT9Limt7vOmFpKxeFeYdF8JGFVY2B/qBf7nn0f2f3448+NlnchMPzxa0lv9FXJV1OLZuMUlOLWbb9rwtBEBGCyv+kPNpRF3b2xzPFMIVieFdeelntPovtD6HQBVaT+JbznB+Zjz3MNEPr1IM0ANapgekFV46W0lRCsJPX60Xy5do0j3Ov8zPJ2TwxN9pHNkqTqAe/oBIQd163TqKWBdCSdmj+IV5xKvot9IkFLBnCuu4gPNhjY9yNTicN97xbkyCLV1bgCAphNT05UbujQy21GNcYMKWgjFAION2TEXnhwrmgCKKtaMzBMA67SmsXeO7YA8735t37OFcl6z3zzFwnALBnVaS3sp/Zf05Spzqs8jC7nDLFqd/xJ7Sh7LjO4wLuGH1HZj9DbKxvQDrXcEm/gvP9uta8i7/SJvxWQeD6lp6i9ZI70Ra58yvyxsdHz1r7xA==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-encryption-key
      namespace: quantified-self
