apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.42
    helm:
      valuesObject:
        existingEncryptionKeySecret: n8n-encryption-key
        main:
          persistence:
            enabled: true
            storageClass: nfs-quantified-self
            size: 5Gi
          extraEnvVars:
            N8N_SECURE_COOKIE: "false"
          extraSecretNamesForEnvFrom:
            - n8n-credentials
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: quantified-self
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
