apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    chart: goldilocks
    targetRevision: 10.3.0
    helm:
      valuesObject:
        controller:
          resources:
            requests:
              cpu: 25m
              memory: 250Mi
        dashboard:
          resources:
            requests:
              cpu: 25m
              memory: 250Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
