apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-quantified-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      valuesObject:
        nfs:
          server: 192.168.1.69
          path: /volume1/quantified-self
        storageClass:
          name: nfs-quantified-self
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
